### ISSUE TITLE
Error with WCGBTS

### ISSUE THREAD

**Issue by AquaAuma** [James-Thorson/FishData#21]
I get an error when I run the following line (only for the WCGBTS survey):
`WCGBTS = download_catch_rates( survey="WCGBTS", species_set=Sci_name, localdir=DataFile )`

Data are downloaded and then I get this error message:
`Error in Data_tmp[, year_column] : incorrect number of dimensions`

Any idea where this might come from?
Thanks

**Comment by James-Thorson-NOAA** [comment]
I'm sorry but I don't really have time to maintain this code.  Looking at the issue, I'm guessing that I accepted a pull request from someone changing the code for subfunction `remove_header_rows`, to fix an issue with another region, and it broke funcitonality for West Coast data.

I'd love for someone to volunteer to make an "integrated test" that loops through regions and confirms its working for each, to use periodically and/or when checking pull requests.  Until that's in place, I doubt I will spend time fixing issues except for my own personal uses.

Hopefully its still useful for showing where data live online.

**Comment by afredstonhermann** [comment]
Here's what's going on, I think. In `download_catch_rates.R`, the West Coast annual survey has been updated to:
```
    files = 2003:2019
```
However the 2019 data does not exist in the data source yet, so it returns an empty object when trying to fetch that year's dataset, and throws an error. @James-Thorson-NOAA can I submit a PR to change it back to 2003:2018 for now (or do you just want to make the change)?

**Comment by afredstonhermann** [comment]
@AquaAuma let me know if this resolves your issue, happy to help troubleshoot further.

**Comment by AquaAuma** [comment]
Thank you Alexa for finding out the problem
I modified the function 'download_catch_rates' but hand on R, and changed `files=2003:2019` to `files=2003:2018` and it worked!
