### ISSUE TITLE
Suggestion for future versions

### ISSUE THREAD

**Issue by marcelxelo** [James-Thorson/FishData#27]
Hey there,

No issues here, but rather a suggestion for possible future versions :)

I was just running the add_missing_zeros() function from your package for a dataset with lots of species. I realized at some point I didin't know how far I was in the process and though it might be relevant to get an update on the progress of the function at the same time as it tells the processed species. Therefore, I suggest to modify as such a small part of the function (which is repeated several times within the function):
Before: message("Finished processing for ", species_set[p])
After: message("Finished processing for ", species_set[p], " (", p, "/", length(species_set), ")")

Hope you find my suggestion useful.

Cheers,
Marcel

**Comment by James-Thorson-NOAA** [comment]
Thanks for the feedback and interest!  However, `FishData` is basically a demo, and not really intended for operational use.  Since writing `add_missing_zeros`, I personally have switched entirely to using `tapply` to do the same thing.  

Feel free to email me about your use-case and always happy to hear about interesting work :)

**Comment by marcelxelo** [comment]
Indeed using the tapply seems as it should be much more efficient. Would you mind providing the code you use when using tapply?

Cheers,
Marcel

**Comment by James-Thorson-NOAA** [comment]
along the lines of:

```R
Data = tapply( Data$N, INDEX=list('station'=Data$station,'length'=Data$length,'survey'=Data$survey), FUN=sum )
Data = ifelse( is.na(Data), 0, Data )

Data = cbind( expand.grid(dimnames(Data)), "N"=as.vector(Data) )
```

**Comment by marcelxelo** [comment]
Much more efficient indeed! Thanks!

**Comment by marcelxelo** [comment]
I have taken the time to do some checking and (with the right treatment) you end up with the same output, but much much faster!
