### ISSUE TITLE
New error in example usage

### ISSUE THREAD

**Issue by DanOvando** [James-Thorson/FishData#6]
Diving back into this, after running
```
devtools::install_github("james-thorson/FishData")
Database = FishData::download_catch_rates( survey="EBSBTS", species_set=20 )
```

Getting 
```
Error in FUN(X[[i]], ...) : invalid 'type' (character) of argument

```

Used to work... I'll try and see if I can figure out what's going on this weekend.

**Comment by James-Thorson** [comment]
Ok I also asked curry Cunningham to change the name for AFSC downloads to
include 2017 data, he said he'd look in few weeks

**Comment by James-Thorson** [comment]
OK the newest merge appears to fix this issue, which was caused by line 49,999 of each EBS CSV available online having the same column headers as line 1
