### ISSUE TITLE
Fixing errors in AIBTS, GOABTS, and WCGHL

### ISSUE THREAD

**Issue by DanOvando** [James-Thorson/FishData#9]
#8 fixed EBSBTS query, some issues remain with the other surveys. 

- The column names of the wcghl appear to have changed

- The same header names at row 49,999 problem occurs in GOABTS and AIBTS (and some NAs in year for AIBTS

I believe I've fixed these issues, reviewing now and will submit a pull request in a few

**Comment by James-Thorson** [comment]
Yes, I expect that GOABTS and AIBTS had the same weird issue when they updated to 2017 data.  Thanks for thinking to fix those!

**Comment by DanOvando** [comment]
Sure thing, thanks for putting this all together (as you can tell I'm getting a lot of use out of it at the moment). Let me know if you need anything else on this.
